name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0

      - name: Merge (ff-only) main -> deployment
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git branch deployment remotes/origin/deployment
          git checkout deployment
          git merge --ff-only main
          git push
